---
  - name: exeuting cmd
    hosts: serverb
    tasks:
      - name: execute cmd
        ansible.builtin.command:
          cmd: "{{ item }}"
        loop:
          - hostname
          - date
          - whoami
        register: cmd_output

      - name: print the value
        ansible.builtin.debug:
          msg: output of cmd is {{ item['stdout_lines'] }}
        loop: "{{ cmd_output['results'] }}"

