---
  - name: create partition using roles
    hosts: serverb
    vars:
      storage_volumes:
        - name: mydisk
          type: disk
          disks:
            - /dev/sdb
          fs_type: ext4
          mount_point: /mnt/roles
    pre_tasks:
      - name: create mount point
        ansible.builtin.file:
          path: /mnt/roles
          state: directory
    roles:
      - redhat.rhel_system_roles.storage
