---
  - name: getting stat
    hosts: serverc
    tasks:
      - name: getting status
        ansible.builtin.stat:
          path: /home/student/ansible.cfg
        register: result

      - name: print the info
        debug:
          var: result
